steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - frontend/Dockerfile
      - --build-arg
      - NEXT_PUBLIC_API_URL=$_NEXT_PUBLIC_API_URL
      - -t
      - $_IMAGE
      - .   # build context = repo root

images:
  - $_IMAGE
